# This is a basic workflow to help you get started with Actions

name: Deploy MSBuild CI (self hosted)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: dev
        type: choice
        options:
        - DevGIP
        - prodTBD
      version:
        description: 'Version number'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-artifact:
    if: ${{ github.event.inputs.version != 'main' }}
      
    runs-on: ubuntu-latest
    
    steps:
      - name: Fetch asset from release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: '${{ github.repository }}'
          version: 'tags/${{ github.event.inputs.version }}'
          file: 'setup_loto.zip' 
          token: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ github.event.repository.name }}-${{ github.event.inputs.version }}
          path: ${{ github.event.repository.name }}-${{ github.event.inputs.version }}
          retention-days: 1
